### ISSUE TITLE
Разработаь мигратор для БД

### ISSUE THREAD

**Issue by demosglok** [horba/IntelliGram-D#1]
Разработать отдельный проект (консольную утилиту) которая будет выполнять миграции - изменения структуры БД. для того что б все изменения структуры оставались в дереве исходников в системе контроля версий.

выглядит как программа, которая проходит по массиву миграций (об этом ниже) и для каждой миграции проверяет, она уже была применена , или нет. если не была - то применяет ее

каждая миграция - это отдельный класс где есть один метод Apply (применить) в котором написаны запросы SQL на изменение структуры БД (добавление, изменение или удаление таблиц, колонок) и метод Revert который возвращает все как было (удаляет добавленные колонки, таблицы и т.п.)

проверять что миграция применена можно например храня список всех примененных миграцией в одной служебной табличке и сверяясь с ней каждый раз. ну и после применения миграции добавлять в эту табличку запись с id миграции.

**Comment by siriak** [comment]
Можно мне это выдать? А то нет галочки чтобы самому себе назначить)

**Comment by horba** [comment]
@siriak Посмотрите, пожалуйста. Так должно получаться: http://joxi.ru/VrwdpVZiKwXPdm

**Comment by siriak** [comment]
Миграции хранятся InstaBotPrototype\DBMigrator\bin\Debug\Migrations, но этот путь игнорируется гитигнором. Стоит комитить миграции или как-то по-другому их добавить? Они должны быть в подпапке Migrations папки с екзешником.

**Comment by demosglok** [comment]
в bin/debug ничего не должно хранится. эта папка генерируется целиком студией. 
не стоит коммитить миграции, которые в bin/debug 
можешь просто добавить в дереве с исходниками на одном уровне с .cs файлами, папку migrations и ложит туда. а из bin/debug будешь доступаться по относительному пути .
ну или что б не страдать со всеми этими путями, таки попробовать каждую миграцию как отдельный класс делать Migrations/Migration20171111_1331.cs
