### ISSUE TITLE
интеграция с azure

### ISSUE THREAD

**Issue by demosglok** [horba/IntelliGram-D#15]
разобраться как работает Microsoft azure, создать бесплатный аккаунт и выложить туда hello-word'овское приложение (если проблемы - спрашивайте)

**Comment by groleore** [comment]
http://inteligramazuretest.azurewebsites.net/
Что-то еще делать по таске? Или брать следующую?

**Comment by horba** [comment]
Пока достаточно. Работай над другими тасками.
