### ISSUE TITLE
сервис для авторизации

### ISSUE THREAD

**Issue by demosglok** [horba/IntelliGram-D#18]
создать сервис для авторизации который имеет методы Login и Register. для логина проверяет наличие такого логина в табличке Users и сверяет пароль (потом будем хеши сверять). если совпали, то в этой же табличке Users обновляется поле LastLogin и генерируется некий Identifier (по сути временный токен) который и возвращается

**Comment by siriak** [comment]
Какого типа id? GUID??
И какую структуру имеет табличка Users? Точно нужны поля Логин, Хеш пароля и Ласт логин.

**Comment by demosglok** [comment]
id можешь хоть int хоть GUID
как удобно

про структруту  таблички - подумай сам и те которые нужны поля добавь. 
можно заодно опросить всех членов команды что они думают про поля в табличке юзерс. может кто-то работает над задачей в которой нужно будет какое-то поле.  как получишь понимание, какие поля нужны, так и добавляй их
