### ISSUE TITLE
соединить форму в веб-приложении и бота

### ISSUE THREAD

**Issue by demosglok** [horba/IntelliGram-D#36]
после тасок #34 и #35 реализовать интеграцию бота и странички
на страничке рядом со ссылкой на бота выводится (генерируется) уникальный ключ, который сохраняется в базу (пусть в табличку юзеров)
когда бот получает этот ключ, он находит по этому ключу в табличке юзеров нужного юзера и сохраняет user_id в свою табличку что б связать user_id и telegram_user_id

(уточняйте подробности)

**Comment by groleore** [comment]
Было в одном пулл реквесте с #35.
