### ISSUE TITLE
how is it work

### ISSUE THREAD

**Issue by Mehran** [horba/IntelliGram-D#38]
how installing ?

**Comment by horba** [comment]
It's a students' project and still under development.

**Comment by Mehran** [comment]
Im interesting to know how it work, can send photo/videos through telegram?

**Comment by horba** [comment]
It is still under development (early stage) and no working prototype available
once it'll be ready we'll surely send you photo and video together with brief description

**Comment by siriak** [comment]
I'm closing the issue because this project isn't under active development and most likely will never have a working version.
