### ISSUE TITLE
класс логгер

### ISSUE THREAD

**Issue by demosglok** [horba/IntelliGram-D#45]
написать класс для логгирования. можно заюзать log4net
юз-кейз такой:
в конструктор всех контроллеров и сервисов будем передавать экземпляр Logger
если он не null то сохраняем этот экземпляр во внутренней переменной, иначе инициализируем новый.
потом в разных местах программы (методов классов) пишем
loggerInstance.WriteError($"some error message with {param}")
loggerInstance.WriteWarning($"some warning message with {param}")
loggerInstance.WriteInfo($"some info message with {param}")
loggerInstance.WriteDebug($"some debug message with {param}")

в зависимости от настроек все сообщения отправленные в лог пишутся в файл (потом еще можно будет в бд сохранять)

предусмотреть возможность установки уровня логгирования в файле конфигурации (app.conf)
для уровня error пишутся только ошибки (WriteError) все остальные игнорируются
для уровня warning пишутся предупрежения и ошибки (WriteWarning и WriteError)
для уровня into пишутся уведомления, предупреждения и ошибки (WriteInfo, WriteWarning, WriteError)
для уровня debug пишется все (включая WriteDebug)

**Comment by siriak** [comment]
Зачем передавать экземпляр в конструкторы? Не лучше ли сделать его в статической переменной?
Писать лог в бд это вроде как плохо и для  этого есть специальные системы, разве нет?
Создание этих полей в каждом классе входит в задание?
