### ISSUE TITLE
интеграция с инстаграммом и recognition api

### ISSUE THREAD

**Issue by demosglok** [horba/IntelliGram-D#46]
после выполнения задачи 44 сделать в нашем солюшене отдельный проект, в котором реализовать сервис по обработке фоток из инстаграмма. 
Сервис берет конфигурации и настройки как из своего файла app.config так и из бд (то что туда для юзеров понаписывали), парсит странички инстаграмные всех юзеров, и распознает картинки на них при помощи image recognition что б получить текстовое описание. 

в текстовом описании от recognition api плюс текстовом описании самой картинки ищет ключевое слово

**Comment by siriak** [comment]
Этот сервис это тоже консольная утилита?
