### ISSUE TITLE
доделать полноценную связку телеграмбота и юзера

### ISSUE THREAD

**Issue by demosglok** [horba/IntelliGram-D#49]
у юзера в конфиге есть ссылка на телеграм бота. возле нее число, которое генерится на бекенде и показывается юзеру и записывается в базу. 

юзер клацает на ссылку на бота, стартует бота, бот спрашивает его число (ключ), юзер вводит тот ключ, который был у него на страничке конфигурации, бот связывает id юзера в телеге (chat_id  & user_id) с id юзера в нашей системе (поискав сгенеренный ключ в табличке сгенеренных ключей, где есть сгенеренный ключ и соответствующий user_id нашего юзера в нашей системе)

если есть вопросы - уточняйте

**Comment by groleore** [comment]
Ключ нужно вводить только при первом запуске бота? (Тогда, если в таблице уже есть chat_id и telegram_user_id, то ключ вообще не выводить пользователю). Или каждый раз?

**Comment by groleore** [comment]
Было выполнено в тасках №35 и №36.
