### ISSUE TITLE
фронтенд - добавить кнопку и форму для логина

### ISSUE THREAD

**Issue by demosglok** [horba/IntelliGram-D#6]
сверстать форму для логина пользователя и добавить кнопку Login по нажатию накоторую будет показываться эта форма в виде всплывающего модального окна

**Comment by vladkvts** [comment]
Уже готова форма и кнопка логина и  регистрации, что с ними делать ?

**Comment by demosglok** [comment]
а какие есть варианты, что с ними делать?

**Comment by vladkvts** [comment]
Нужна или основная страница, куда их закинуть, или использовать мою ( с кнопками и формами ) как эту основу

**Comment by demosglok** [comment]
есть основная страница, можно пока их туда добавить как спрятанные ( display:none) элементы и показывать ($('#register-dialog').show()) при нажатии на соответствующую кнопку. или вообще заиспользовать какой-нить jquery-ui с его dialog'ами
