### ISSUE TITLE
backend - AuthController

### ISSUE THREAD

**Issue by demosglok** [horba/IntelliGram-D#7]
Разработать AuthController с методами Login и Register которые пока отвечают пустым ответом и могут вызываться из фронтенда

**Comment by siriak** [comment]
Какие аргументы и возвращаемые значения у этих методов?

**Comment by demosglok** [comment]
эм, а какие варианты ты бы мог предложить?

давай уходить от подхода "я кодер, дайте мне спецификацию, я сделаю согласно нее" в сторону бизнес-подхода "я понимаю что должен делать продукт и исходя из этого сам стараюсь дополнять спецификации что б результат соответствовал общим ожиданиям от продукта". второй подход гораздо выше ценится (особенно в сша). типа бизнес-ориентированность или продукто-ориентированность , аналитиз и все такое вместо тупого кодирования согласно спецификации (кодировать согласно спеки скоро AI будет уметь и так)
