### ISSUE TITLE
Словари для тэгов и топиков

### ISSUE THREAD

**Issue by demosglok** [horba/IntelliGram-D#73]
Необходимо улучшить юзабилити по выбору тегов и топиков, для этого нужно выполнить несколько пунктов:

- сделать прозрачнее способ задания нескольких топиков или тегов - уйти от использования одной строки и разделения через запятую. нужно исследовать вопрос и выбрать подходящий ui-компонент.
- завести подсказки для пользователя для вводимых тегов и топиков - т.е. когда пользователь вводит буквы появляется подсказка о том, что это может быть и на каждой новой букве обновляется.

Таска связана с другими тасками: #75 #77 

В рамках этой таски можно завести подзадачи.

**Comment by AkulovBogdan** [comment]
![tagtopicmockup](https://user-images.githubusercontent.com/31021059/36129658-f09931e8-1070-11e8-98dd-5c1b0772a0d6.png)
Tag/Topic UI
