### ISSUE TITLE
Application mocks

### ISSUE THREAD

**Issue by horba** [horba/IntelliGram-D#75]
Нарисовать мокап для основных страниц приложения. 
Можно использовать нинзя мокс.
Предусмотреть адаптивность.

Скооперироваться с #73 - на мокапах должен быть показан компонент, выбранный для задания топиков и тегов.

- [ ] Мокапы десктопной версии 
- [ ] Мокапы мобильной версии

**Comment by AkulovBogdan** [comment]
https://ninjamock.com/s/T6Z96Wx
